### ISSUE TITLE
checklist for 2021.06 pilot

### ISSUE THREAD

**Issue by boegel** [EESSI/software-layer#118]
* [x] new container images in GitHub container registry `ghrc.io`
* [x] Allow overriding MPI family via rpath (#116)
* [x] update build script for EasyBuild v4.4.0 (#119)
* [x] use script to create tarball to ingest on build node (#111)
* [x] **automate ingestion into EESSI pilot repository**
* build software for 2021.06
  * [x] `aarch64/generic`
  * [x] `aarch64/graviton2`
  * [x] `ppc64le/generic`
  * [x] `ppc64le/power9`
  * [x] `x86_64/generic`
  * [x] `x86_64/amd/rome`
  * [x] `x86_64/intel/haswell`
  * [x] `x86_64/intel/skylake_avx512`
* [x] deploy init scripts for 2021.06

**Comment by bedroge** [comment]
All done, 2021.06 is available, so I'm closing this issue.
